version: "3.9"

services: 

  # nginx:
  #   service will be here

  # postgresql-db:
  #   service will be here

  django-backend:
    restart: always
    build:
      context: ./django-backend
    image: djangobackend # name the resulted image: https://docs.docker.com/compose/compose-file/compose-file-v3/#build
  # certbot:
  #   service will be here

# volumes: 
#   not sure if needed at the moment...